#!/usr/bin/env python3
"""summarize.py -- keep registry.yaml and blob checksums fresh.

Usage:
    python tools/summarize.py registry            # rebuild summary + stews list
    python tools/summarize.py sha256 <file>       # print one file's sha256
    python tools/summarize.py stats               # print a human-readable table

The `registry` subcommand rewrites registry.yaml from the stews/ directory.
Only the `summary` block is machine-owned; the `stews` list is regenerated
whole from meta.yaml files. The docstring header is preserved.
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write("error: PyYAML is required (pip install pyyaml)\n")
    sys.exit(2)

REPO_ROOT = Path(__file__).resolve().parent.parent
REGISTRY = REPO_ROOT / "registry.yaml"
STEWS_DIR = REPO_ROOT / "stews"

try:
    yaml.SafeDumper.add_representer(
        type(None), lambda dumper, _value: dumper.represent_scalar("tag:yaml.org,2002:null", "")
    )
except Exception:  # pragma: no cover
    pass


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh) or {}


def sorted_stew_dirs() -> list[Path]:
    if not STEWS_DIR.exists():
        return []
    return sorted(p for p in STEWS_DIR.iterdir() if p.is_dir())


def collect_entries() -> list[dict]:
    entries = []
    for stew_dir in sorted_stew_dirs():
        meta_path = stew_dir / "meta.yaml"
        if not meta_path.exists():
            continue
        meta = load_yaml(meta_path)
        entries.append(
            {
                "id": meta.get("id"),
                "slug": meta.get("slug"),
                "status": meta.get("status"),
                "path": str(stew_dir.relative_to(REPO_ROOT)),
                "content_sha256": (meta.get("content") or {}).get("sha256"),
                "generation": (meta.get("lineage") or {}).get("generation"),
                "curated_by": (meta.get("community") or {}).get("curator"),
                "tags": (meta.get("community") or {}).get("tags", []),
            }
        )
    # seeded entries structurally guarantee required keys even when metadata is
    # incomplete; validate.py is the gatekeeper that flags such gaps.
    return [e for e in entries if e["id"]]


def build_registry() -> dict:
    entries = collect_entries()
    by_status: dict[str, int] = {}
    for entry in entries:
        status = entry.get("status") or "unknown"
        by_status[status] = by_status.get(status, 0) + 1
    generated_at = datetime.datetime.now(datetime.timezone.utc).replace(
        microsecond=0
    ).isoformat().replace("+00:00", "Z")
    return {
        "schema": "stew.registry@1.0",
        "generated_at": generated_at,
        "summary": {
            "total_stews": len(entries),
            "by_status": dict(sorted(by_status.items())),
        },
        "stews": entries,
    }


def write_registry() -> None:
    data = build_registry()
    header = (
        "# registry.yaml -- full-pot index.\n"
        "# Machine-generated by tools/summarize.py registry. Do not hand-edit.\n"
        "# The `stews` list mirrors the stews/ directory (verified by tools/validate.py).\n\n"
    )
    body = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, default_flow_style=False)
    REGISTRY.write_text(header + body, encoding="utf-8")
    print(f"registry.yaml written: {data['summary']['total_stews']} stews")
    print(
        "note: sealed stews are deliberately omitted from the index (see GOVERNANCE.md); "
        "validate.py treats that as legal."
    )


def print_stats() -> None:
    entries = collect_entries()
    if not entries:
        print("no stews in stews/")
        return
    widths = {k: len(k) for k in ("id", "slug", "status", "generation", "curated_by")}
    for e in entries:
        widths["id"] = max(widths["id"], len(str(e.get("id"))))
        widths["slug"] = max(widths["slug"], len(str(e.get("slug"))))
        widths["status"] = max(widths["status"], len(str(e.get("status"))))
        widths["generation"] = max(widths["generation"], len(str(e.get("generation"))))
        widths["curated_by"] = max(widths["curated_by"], len(str(e.get("curated_by"))))
    head = " | ".join(k.ljust(widths[k]) for k in ("id", "slug", "status", "generation", "curated_by"))
    print(head)
    print("-+-".join("-" * widths[k] for k in ("id", "slug", "status", "generation", "curated_by")))
    for e in entries:
        print(
            " | ".join(
                str(e.get(k)).ljust(widths[k])
                for k in ("id", "slug", "status", "generation", "curated_by")
            )
        )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="summarize.py")
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("registry", help="rebuild registry.yaml from stews/")
    sub.add_parser("stats", help="print a table of all stews")
    sha = sub.add_parser("sha256", help="print sha256 of a file")
    sha.add_argument("file")
    args = parser.parse_args(argv)

    if args.command == "registry":
        write_registry()
    elif args.command == "stats":
        print_stats()
    elif args.command == "sha256":
        print(sha256_of(Path(args.file)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))